FROM php:5.6-apache

RUN useradd peter -U -G www-data -m
RUN chgrp www-data /var/www
RUN chmod g+rw /var/www

RUN apt-get update \
    && apt-get install -y \
        cron \
        libfreetype6-dev \
        libicu-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        libxslt1-dev \
        git

RUN docker-php-ext-configure \
    gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/

RUN docker-php-ext-install \
    gd \
    intl \
    mbstring \
    mcrypt \
    pdo_mysql \
    soap \
    xsl \
    zip \
    bcmath

RUN a2enmod rewrite

RUN sed -i '1 a memory_limit=2G' /usr/local/etc/php/conf.d/memory-limit.ini


ADD ./mhsendmail /usr/local/bin
RUN echo 'sendmail_path = "/usr/local/bin/mhsendmail --smtp-addr\\=peter.mouses.nl:1025"' >> /usr/local/etc/php/php.ini

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN chmod +x composer.phar
RUN cp composer.phar /usr/local/bin/composer
RUN curl -o /usr/local/bin/magerun https://files.magerun.net/n98-magerun.phar && chmod +x /usr/local/bin/magerun

